### ISSUE TITLE
No messages coming in

### ISSUE THREAD

**Issue by pjmuller** [andreas/go-bayeux-client#1]
Hi Andreas,

long time ago :). thanks to you I really got to use golang for Podio and it has been a bliss ever since. Through our backup service we pump over 300MB of json/s ... without a sweat :).

Trying to get one step further I was playing with the push service, however no messages are coming in, can you tell me what I'm doing wrong?

```
	item, err := podioClient.GetItem(ITEMID)
	if err != nil {
		return
	}

	b := bayeux.NewClient("https://podio.com", nil)
	msgs := make(chan *bayeux.Message)
	item.Push.Subscribe(b, msgs)
	defer b.Close()

	for msg := range msgs {
		fmt.Println("Received message: ", msg)
	}
```

Thanks a lot :)!

**Comment by andreas** [comment]
Hey, happy to hear it's working well for you 😄 

I haven't looked at this for a while, but first thing that comes to mind is to try `bayeux.NewClient("https://push.podio.com/faye", nil)` ([doc](https://developers.podio.com/examples/push)). Let me know if that doesn't work for you.

**Comment by pjmuller** [comment]
Hi Andreas,

damn... now it worked immediately :). Thanks!
Might be relevant to add to the readme (of podio-go or go-bayeux-client) because the current example of go-bayeux-client isn't correct either as `msgs := make(bayeux.Chan)` doesn't exist but should be `msgs := make(chan *bayeux.Message)` I believe..

Ok cool, I'll continue with hacking myself through push notifications!

**Comment by andreas** [comment]
Great! Can I get you to make a PR with the README changes? 😉

**Comment by pjmuller** [comment]
Sorry, did not see you comment until now.
Will try to do a PR for it soon :) !
