### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by halkeye** [andreas/go-bayeux-client#3]
:wave: You have a really well thought out and easy to integrate with library here, and I was hoping you'd add any sort of license so we could use it to pull salesforce events. As it stands due to the lack of license you are the only person able to use it.

My personal recommendation is MIT as it pretty much says do what you want but I'm not responsible - https://choosealicense.com/licenses/mit/

Thanks

**Comment by andreas** [comment]
Thanks for the input! Added a license now.
